//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conf
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bullhorn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bullhorn_2x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_2x = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int feed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int feed_2x = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int map = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int map_2x = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int microphone = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int microphone_2x = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int star = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int star_2x = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int WindowTitle = 2130837517;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int Bio = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int Brief = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int DateTimeDisplay = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int FavouriteButton = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int List = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int Name = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int Room = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int SessionList = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int SpeakerList = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int Subtitle = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int TagList = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int Time = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Title = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int header = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int headerlayout = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int scroller = 2131165190;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Favourites = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FavouritesItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Session = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Sessions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Sessions2Item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SessionsItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Speaker = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Speakers = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SpeakersItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Tags = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TagsItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int WindowTitle = 2130903053;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int conf = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CustomTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CustomWindowTitleBackground = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
